SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE books_categories;
TRUNCATE TABLE books;
TRUNCATE TABLE categories;

ALTER TABLE categories AUTO_INCREMENT = 1;
ALTER TABLE books AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
